version: '3.8'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: user
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped

  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped

  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_API=3
      - ALLOW_NONE_AUTHENTICATION=yes
    volumes:
      - etcd-data:/etcd-data
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: "minioadmin"           # 用户名
      MINIO_ROOT_PASSWORD: "minioadmin123"     # 密码
    ports:
      - "9000:9000"   # MinIO 对象存储端口
      - "9001:9001"   # MinIO 控制台端口
    command: server /data --console-address ':9001'   #指定容器中的目录 /data
    volumes:
      - minio-data:/data
    restart: unless-stopped

volumes:
  mysql-data:
  redis-data:
  etcd-data:
  minio-data:
