// Code generated by goctl. DO NOT EDIT.
// Source: comment.proto

package server

import (
	"context"

	"zhihu/app/comment/internal/logic"
	"zhihu/app/comment/internal/svc"
	"zhihu/app/comment/pb/comment"
)

type CommentServer struct {
	svcCtx *svc.ServiceContext
	comment.UnimplementedCommentServer
}

func NewCommentServer(svcCtx *svc.ServiceContext) *CommentServer {
	return &CommentServer{
		svcCtx: svcCtx,
	}
}

func (s *CommentServer) Ping(ctx context.Context, in *comment.Request) (*comment.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

// 获取评论列表
func (s *CommentServer) GetCommentList(ctx context.Context, in *comment.GetCommentListRequest) (*comment.GetCommentListResponse, error) {
	l := logic.NewGetCommentListLogic(ctx, s.svcCtx)
	return l.GetCommentList(in)
}

// 发布评论
func (s *CommentServer) PublishComment(ctx context.Context, in *comment.PublishCommentRequest) (*comment.PublishCommentResponse, error) {
	l := logic.NewPublishCommentLogic(ctx, s.svcCtx)
	return l.PublishComment(in)
}

// 删除评论
func (s *CommentServer) DeleteComment(ctx context.Context, in *comment.DeleteCommentRequest) (*comment.DeleteCommentResponse, error) {
	l := logic.NewDeleteCommentLogic(ctx, s.svcCtx)
	return l.DeleteComment(in)
}
