// Code generated by goctl. DO NOT EDIT.
// Source: video.proto

package server

import (
	"context"

	"zhihu/app/video/internal/logic"
	"zhihu/app/video/internal/svc"
	"zhihu/app/video/pb/video"
)

type VideoServer struct {
	svcCtx *svc.ServiceContext
	video.UnimplementedVideoServer
}

func NewVideoServer(svcCtx *svc.ServiceContext) *VideoServer {
	return &VideoServer{
		svcCtx: svcCtx,
	}
}

// 获取视频上传的预签名 URL
func (s *VideoServer) GetUploadURL(ctx context.Context, in *video.GetUploadURLRequest) (*video.GetUploadURLResponse, error) {
	l := logic.NewGetUploadURLLogic(ctx, s.svcCtx)
	return l.GetUploadURL(in)
}

func (s *VideoServer) Publish(ctx context.Context, in *video.PublishRequest) (*video.PublishResponse, error) {
	l := logic.NewPublishLogic(ctx, s.svcCtx)
	return l.Publish(in)
}

func (s *VideoServer) Detail(ctx context.Context, in *video.DetailRequest) (*video.DetailResponse, error) {
	l := logic.NewDetailLogic(ctx, s.svcCtx)
	return l.Detail(in)
}
