// Code generated by goctl. DO NOT EDIT.
// Source: follow.proto

package server

import (
	"context"

	"zhihu/app/follow/follow"
	"zhihu/app/follow/internal/logic"
	"zhihu/app/follow/internal/svc"
)

type FollowServer struct {
	svcCtx *svc.ServiceContext
	follow.UnimplementedFollowServer
}

func NewFollowServer(svcCtx *svc.ServiceContext) *FollowServer {
	return &FollowServer{
		svcCtx: svcCtx,
	}
}

func (s *FollowServer) Ping(ctx context.Context, in *follow.Request) (*follow.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
