// Code generated by goctl. DO NOT EDIT.
// Source: follow.proto

package server

import (
	"context"

	"zhihu/app/follow/internal/logic"
	"zhihu/app/follow/internal/svc"
	"zhihu/app/follow/pb/follow"
)

type FollowServer struct {
	svcCtx *svc.ServiceContext
	follow.UnimplementedFollowServer
}

func NewFollowServer(svcCtx *svc.ServiceContext) *FollowServer {
	return &FollowServer{
		svcCtx: svcCtx,
	}
}

func (s *FollowServer) CheckService(ctx context.Context, in *follow.PingRequest) (*follow.PingResponse, error) {
	l := logic.NewCheckServiceLogic(ctx, s.svcCtx)
	return l.CheckService(in)
}

func (s *FollowServer) FollowAction(ctx context.Context, in *follow.FollowActionRequest) (*follow.FollowActionResponse, error) {
	l := logic.NewFollowActionLogic(ctx, s.svcCtx)
	return l.FollowAction(in)
}

func (s *FollowServer) ListFollowing(ctx context.Context, in *follow.GetFollowListRequest) (*follow.GetFollowListResponse, error) {
	l := logic.NewListFollowingLogic(ctx, s.svcCtx)
	return l.ListFollowing(in)
}

func (s *FollowServer) ListFollowers(ctx context.Context, in *follow.GetFollowerListRequest) (*follow.GetFollowerListResponse, error) {
	l := logic.NewListFollowersLogic(ctx, s.svcCtx)
	return l.ListFollowers(in)
}
