// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"zhihu/app/applet/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/email-login",
				Handler: EmailLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/email-register",
				Handler: EmailRegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/verification",
				Handler: VerificationHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/:user_id",
					Handler: UserInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:user_id/avatar",
					Handler: GetAvatarHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/:user_id/update",
					Handler: UserInfoUpdateHandler(serverCtx),
				},
			}...,
		),
		rest.WithSignature(serverCtx.Config.Signature),
		rest.WithPrefix("/v1/user"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.MustLoginMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/:obj_id/like",
					Handler: LikeActionHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/:obj_id/likeNum",
					Handler: LikeNumHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1/like"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.MustLoginMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/:filename",
					Handler: UploadUrlHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/publish",
					Handler: PublishHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1/video"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/user/like-list",
					Handler: UserLikeListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/video-list",
					Handler: UserVideoListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/video-list",
					Handler: VideoListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1/video"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.MustLoginMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/comment-list",
					Handler: CommentListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/commment-publish",
					Handler: CommentPublishHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/delete",
					Handler: CommentDeleteHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1/comment"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.MustLoginMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/check-follow",
					Handler: CheckFollowHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/follow-action",
					Handler: FollowActionHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/follow-list",
					Handler: ListFollowHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1/follow"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/chat/connect/:user_id",
				Handler: ChatConnectHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/ws"),
	)
}
