// Code generated by goctl. DO NOT EDIT.
// Source: video.proto

package videoclient

import (
	"context"

	"zhihu/app/video/pb/video"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DetailRequest        = video.DetailRequest
	DetailResponse       = video.DetailResponse
	GetUploadURLRequest  = video.GetUploadURLRequest
	GetUploadURLResponse = video.GetUploadURLResponse
	PublishRequest       = video.PublishRequest
	PublishResponse      = video.PublishResponse
	VideoFeed            = video.VideoFeed

	Video interface {
		// 获取视频上传的预签名 URL
		GetUploadURL(ctx context.Context, in *GetUploadURLRequest, opts ...grpc.CallOption) (*GetUploadURLResponse, error)
		Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
		Detail(ctx context.Context, in *DetailRequest, opts ...grpc.CallOption) (*DetailResponse, error)
	}

	defaultVideo struct {
		cli zrpc.Client
	}
)

func NewVideo(cli zrpc.Client) Video {
	return &defaultVideo{
		cli: cli,
	}
}

// 获取视频上传的预签名 URL
func (m *defaultVideo) GetUploadURL(ctx context.Context, in *GetUploadURLRequest, opts ...grpc.CallOption) (*GetUploadURLResponse, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.GetUploadURL(ctx, in, opts...)
}

func (m *defaultVideo) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.Publish(ctx, in, opts...)
}

func (m *defaultVideo) Detail(ctx context.Context, in *DetailRequest, opts ...grpc.CallOption) (*DetailResponse, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.Detail(ctx, in, opts...)
}
