// Code generated by goctl. DO NOT EDIT.
package types

type EmailLoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type EmailLoginResponse struct {
	UserId      int64  `json:"user_id"`
	AccessToken string `json:"token"`
}

type EmailRegisterRequest struct {
	UserName   string `json:"name"`
	Password   string `json:"password"`
	RePassword string `json:"re_password"`
	Email      string `json:"email"`
	Code       string `json:"code"`
}

type EmailRegisterResponse struct {
	UserId      int64  `json:"user_id"`
	AccessToken string `json:"token"`
}

type LikeVideoRequest struct {
	ActionType string `json:"action_type"`
	BizId      string `json:"biz_id"`
	UserId     int64  `json:"user_id"` // 用户ID
	ObjId      int64  `path:"obj_id"`  // 对象ID
}

type UploadUrlResponse struct {
	VideoUrl string `json:"video_url"`
	CoverUrl string `json:"cover_url"`
}

type UserInfoResponse struct {
	UserId   int64  `json:"user_id"`
	UserName string `json:"name"`
	Email    string `json:"email"`
}

type VerificationRequest struct {
	Email string `json:"email"`
}

type VerificationResponse struct {
}
