// Code generated by goctl. DO NOT EDIT.
package types

type EmailLoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type EmailLoginResponse struct {
	UserId      int64  `json:"user_id"`
	AccessToken string `json:"token"`
}

type EmailRegisterRequest struct {
	UserName   string `json:"name"`
	Password   string `json:"password"`
	RePassword string `json:"re_password"`
	Email      string `json:"email"`
	Code       string `json:"code"`
}

type EmailRegisterResponse struct {
	UserId      int64  `json:"user_id"`
	AccessToken string `json:"token"`
}

type LikeActionRequest struct {
	ActionType string `json:"action_type"`
	BizId      string `json:"biz_id"`
	ObjId      int64  `path:"obj_id"` // 对象ID
}

type LikeActionResponse struct {
	Status string `json:"status"`
}

type PublishHandlerRequest struct {
	AuthorId    int64  `json:"author_id"`
	VideoId     int64  `json:"video_id"`
	VideoUrl    string `json:"video_url"`
	CoverUrl    string `json:"cover_url"`
	Title       string `json:"title"`
	Description string `json:"description"`
}

type PublishHandlerResponse struct {
	VideoId int64 `json:"video_id"`
}

type UploadUrlResponse struct {
	VideoUrl string `json:"video_url"`
	CoverUrl string `json:"cover_url"`
}

type UserInfoResponse struct {
	UserId   int64  `json:"user_id"`
	UserName string `json:"name"`
	Email    string `json:"email"`
}

type VerificationRequest struct {
	Email string `json:"email"`
}

type VerificationResponse struct {
}

type VideoInfo struct {
	VideoId      int64
	AuthorId     int64
	AuthorName   string
	AuthorAvatar string
	VideoUrl     string
	Title        string
	CoverUrl     string
	Description  string
	CommentCount int64
	LikeCount    int64
}

type VideoListRequest struct {
	Page      int64 `path:"page"`
	Cursor    int64 `path:"cursor"`
	Feed_type int32 `query:"limit"`
}

type VideoListResponse struct {
	VideoList []VideoInfo `json:"video_list"`
}
